"auth_tokens"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"auth_tokens"	"user_id"	"uuid"	"NO"	
"auth_tokens"	"token_hash"	"character varying"	"NO"	
"auth_tokens"	"purpose"	"character varying"	"NO"	
"auth_tokens"	"expires_at"	"timestamp with time zone"	"NO"	
"auth_tokens"	"used"	"boolean"	"NO"	"false"
"auth_tokens"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"awards"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"awards"	"profile_id"	"uuid"	"NO"	
"awards"	"title"	"character varying"	"NO"	
"awards"	"description"	"text"	"YES"	
"awards"	"date_earned"	"date"	"YES"	
"awards"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"highlights"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"highlights"	"profile_id"	"uuid"	"NO"	
"highlights"	"video_url"	"text"	"NO"	
"highlights"	"title"	"character varying"	"YES"	
"highlights"	"sort_order"	"integer"	"NO"	"0"
"highlights"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"martial_arts"	"id"	"integer"	"NO"	"nextval('martial_arts_id_seq'::regclass)"
"martial_arts"	"name"	"character varying"	"NO"	
"profile_martial_arts"	"profile_id"	"uuid"	"NO"	
"profile_martial_arts"	"martial_art_id"	"integer"	"NO"	
"profile_weight_classes"	"profile_id"	"uuid"	"NO"	
"profile_weight_classes"	"weight_class_id"	"integer"	"NO"	
"profiles"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"profiles"	"user_id"	"uuid"	"NO"	
"profiles"	"profile_picture_url"	"text"	"YES"	
"profiles"	"bio"	"text"	"YES"	
"profiles"	"instagram_url"	"text"	"YES"	
"profiles"	"awards_display_mode"	"character varying"	"NO"	"'shelf'::character varying"
"profiles"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"profiles"	"updated_at"	"timestamp with time zone"	"NO"	"now()"
"profiles"	"first_name"	"character varying"	"NO"	"''::character varying"
"profiles"	"last_name"	"character varying"	"NO"	"''::character varying"
"profiles"	"nickname"	"character varying"	"YES"	
"profiles"	"verified"	"boolean"	"NO"	"false"
"profiles"	"date_of_birth"	"date"	"YES"	
"profiles"	"height"	"integer"	"YES"	
"profiles"	"stance"	"character varying"	"YES"	
"profiles"	"team"	"character varying"	"YES"	
"profiles"	"hometown"	"character varying"	"YES"	
"profiles"	"walkout_song"	"character varying"	"YES"	
"profiles"	"walkout_song_artist"	"character varying"	"YES"	
"profiles"	"profile_banner_url"	"text"	"YES"	
"records"	"profile_id"	"uuid"	"NO"	
"records"	"wins"	"integer"	"NO"	"0"
"records"	"losses"	"integer"	"NO"	"0"
"records"	"draws"	"integer"	"NO"	"0"
"records"	"no_contests"	"integer"	"NO"	"0"
"records"	"updated_at"	"timestamp with time zone"	"NO"	"now()"
"records"	"ko"	"integer"	"NO"	"0"
"records"	"submissions"	"integer"	"NO"	"0"
"records"	"total_fights"	"integer"	"NO"	
"reports"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"reports"	"reported_profile_id"	"uuid"	"NO"	
"reports"	"reporter_user_id"	"uuid"	"YES"	
"reports"	"reason"	"text"	"NO"	
"reports"	"status"	"character varying"	"NO"	"'pending'::character varying"
"reports"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"session"	"sid"	"character varying"	"NO"	
"session"	"sess"	"json"	"NO"	
"session"	"expire"	"timestamp without time zone"	"NO"	
"tags"	"id"	"integer"	"NO"	"nextval('tags_id_seq'::regclass)"
"tags"	"profile_id"	"uuid"	"NO"	
"tags"	"tag_text"	"character varying"	"NO"	
"tags"	"sort_order"	"integer"	"NO"	"0"
"users"	"id"	"uuid"	"NO"	"gen_random_uuid()"
"users"	"username"	"character varying"	"YES"	
"users"	"email"	"character varying"	"YES"	
"users"	"password_hash"	"character varying"	"YES"	
"users"	"corner"	"character varying"	"NO"	
"users"	"email_verified"	"boolean"	"NO"	"false"
"users"	"created_at"	"timestamp with time zone"	"NO"	"now()"
"users"	"claimed"	"boolean"	"NO"	"true"
"users"	"is_admin"	"boolean"	"NO"	"false"
"users"	"is_founding_member"	"boolean"	"NO"	"false"
"users"	"is_beta_tester"	"boolean"	"NO"	"false"
"weight_classes"	"id"	"integer"	"NO"	"nextval('weight_classes_id_seq'::regclass)"
"weight_classes"	"name"	"character varying"	"NO"	
"weight_classes"	"gender"	"character varying"	"NO"	
"weight_classes"	"sort_order"	"integer"	"NO"		

"records"	"profile_id"	"profiles"	"CASCADE"
"profile_weight_classes"	"profile_id"	"profiles"	"CASCADE"
"tags"	"profile_id"	"profiles"	"CASCADE"
"highlights"	"profile_id"	"profiles"	"CASCADE"
"awards"	"profile_id"	"profiles"	"CASCADE"
"profile_martial_arts"	"profile_id"	"profiles"	"CASCADE"
"reports"	"reported_profile_id"	"profiles"	"CASCADE"
"profiles"	"user_id"	"users"	"CASCADE"
"auth_tokens"	"user_id"	"users"	"CASCADE"
"reports"	"reporter_user_id"	"users"	"NO ACTION"